### ISSUE TITLE
Runtime error while converting encrypted private key to PKCS#8

### ISSUE THREAD

**Issue by umayr** [youmark/pkcs8#4]
Consider the following snippet:
```go
package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"encoding/pem"
	"fmt"

	"github.com/youmark/pkcs8"
)

func generate(bits int, passphrase string) ([]byte, error) {
	key, err := rsa.GenerateKey(rand.Reader, bits)
	if err != nil {
		return nil, err
	}

	block := &pem.Block{
		Type:  "RSA PRIVATE KEY",
		Bytes: x509.MarshalPKCS1PrivateKey(key),
	}

	if passphrase != "" {
		block, err = x509.EncryptPEMBlock(rand.Reader, block.Type, block.Bytes, []byte(passphrase), x509.PEMCipherAES256)
		if err != nil {
			return nil, err
		}
	}

	return pem.EncodeToMemory(block), nil
}

func convert(pemBytes []byte, passphrase string) ([]byte, error) {
	block, _ := pem.Decode(pemBytes)
	if block == nil {
		return nil, fmt.Errorf("no valid private key found")
	}

	var (
		privateKeyBytes []byte
		privateKey      interface{}
		err             error
	)

	if x509.IsEncryptedPEMBlock(block) {
		privateKeyBytes, err = x509.DecryptPEMBlock(block, []byte(passphrase))
		if err != nil {
			return nil, fmt.Errorf("couldn't decrypt private key")
		}
	} else {
		privateKeyBytes = block.Bytes
	}

	switch block.Type {
	case "RSA PRIVATE KEY":
		privateKey, err = x509.ParsePKCS1PrivateKey(privateKeyBytes)
		if err != nil {
			return nil, fmt.Errorf("couldn't parse der encoded key: %v", privateKeyBytes)
		}
	default:
		return nil, fmt.Errorf("unsupported key type %q", block.Type)
	}

	return pkcs8.ConvertPrivateKeyToPKCS8(privateKey, []byte(passphrase))
}

func main() {
	passphrase := "unicorn"
	pemBytes, err := generate(1024, passphrase)
	if err != nil {
		panic(err)
	}

	_, err = convert(pemBytes, passphrase)
	if err != nil {
		panic(err)
	}
}
```

I'm trying to generate an encrypted RSA based private key and then converting it to PKCS#8. This results into a runtime error:
```
panic: runtime error: slice bounds out of range

goroutine 1 [running]:
github.com/youmark/pkcs8.convertPrivateKeyToPKCS8Encrypted(0x521b80, 0xc4201583c0, 0xc420010b58, 0x7, 0x8, 0x8, 0x43d483, 0xc42004be90, 0x53a0cf, 0x7)
	/home/umayr/Code/go/src/github.com/youmark/pkcs8/pkcs8.go:210 +0x6d5
github.com/youmark/pkcs8.ConvertPrivateKeyToPKCS8(0x521b80, 0xc4201583c0, 0xc42004bee8, 0x1, 0x1, 0x20, 0x270, 0x0, 0x0, 0xc42014e8d0)
	/home/umayr/Code/go/src/github.com/youmark/pkcs8/pkcs8.go:243 +0xc8
main.convert(0xc420164000, 0x3da, 0x778, 0x53a0cf, 0x7, 0x778, 0x0, 0x0, 0xc420000340, 0xc420000340)
	/home/umayr/Code/go/src/github.com/umayr/pkcs8/ref.go:65 +0x3d6
main.main()
	/home/umayr/Code/go/src/github.com/umayr/pkcs8/ref.go:75 +0xa4
exit status 2
```

With a little debugging, I think this line is causing the issue in [`pkcs8.go`](https://github.com/youmark/pkcs8/blob/fb03088258a3ad7505ad72dc9a7fac352e9f3304/pkcs8.go#L210):
```go
pkey = pkey[0 : n+padding]
```

Here `n` is the length of `pkey` and above line is trying to create a slice from `0` to `length of pkey + padding` which should return an error as demonstrated in this [example](https://play.golang.org/p/TIjUE0_Y83).

Replacing this line with:
```diff
diff --git a/pkcs8.go b/pkcs8.go
index 0b6c6e0..dde6818 100644
--- a/pkcs8.go
+++ b/pkcs8.go
@@ -207,7 +207,7 @@ func convertPrivateKeyToPKCS8Encrypted(priv interface{}, password []byte) ([]byt
        padding := aes.BlockSize - len(pkey)%aes.BlockSize
        if padding > 0 {
                n := len(pkey)
-               pkey = pkey[0 : n+padding]
+               pkey = append(pkey, make([]byte, padding)...)
                for i := 0; i < padding; i++ {
                        pkey[n+i] = byte(padding)
                }

```
fixes this issue temporarily. I can have a PR ready for this with more efficient fix.

**Comment by youmark** [comment]
Correct. It throws the error when padding length + pkey length exceeds pkey capacity . Feel free to submit your PR. Thanks umayr.
